#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 04, 2018 10:54:01 PM

import sys
import tkMessageBox
import fo2
import fo2_support
import subprocess
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import fo1_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    fo1_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    fo1_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:
    def use(self):
        tkMessageBox.showinfo("USE", "1. EXCEL SHEET SHOULD BE IN UPPERCASE EXCEPT COLUMN NAMES.INITIALS SHOULD BE IN UPPER CASE AND REST"
                                     " OF THE LETTERS IN LOWER CASE\n2.FOR MERIT ANALYSIS ENTER COLUMN NAME AS ' Merit No '\n3. PLEASE ENTER VALID PATH FOR DATA ANALYSIS \n")

    def continuee(self):
        subprocess.call(" python fO2.py 1", shell=True)
        exit()




    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 9 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 1 -overstrike 0"

        top.geometry("1045x638+130+6")
        top.title("New Toplevel")
        top.configure(background="#595959")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.03, rely=0.06, height=51, width=974)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''SCRUTINY-PROBE''')
        self.Label1.configure(width=974)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.37, rely=0.42, height=54, width=237)
        self.Button1.configure(activebackground="#176b0e")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''HOW TO USE ?''')
        self.Button1.configure(width=237)
        self.Button1.configure(command=self.use)

        self.Button1_1 = Button(top)
        self.Button1_1.place(relx=0.37, rely=0.67, height=54, width=237)
        self.Button1_1.configure(activebackground="#176b0e")
        self.Button1_1.configure(activeforeground="white")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font10)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''CONTINUE''')
        self.Button1_1.configure(command=self.continuee)







if __name__ == '__main__':
    vp_start_gui()



