#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 05, 2018 07:52:06 PM

import sys
import subprocess
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
import fo4_support

import fo41
import fo41_support
import fo42
import fo43
import fo44
import fo45
import fo46
import fo47
import fo48
import fo49
import fo410


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    fo4_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    fo4_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:

    def it(self):
        subprocess.call(" python fO41.py 1", shell=True)
    def civil(self):
        subprocess.call(" python fO42.py 1", shell=True)
    def computer(self):
        subprocess.call(" python fO43.py 1", shell=True)
    def mechanical(self):
        subprocess.call(" python fO44.py 1", shell=True)
    def mechanicalii(self):
        subprocess.call(" python fO45.py 1", shell=True)

    def electrical(self):
        subprocess.call(" python fO46.py 1", shell=True)
    def electricalii(self):
        subprocess.call(" python fO47.py 1", shell=True)
    def entc(self):
        subprocess.call(" python fO48.py 1", shell=True)

    def electronicsii(self):
        subprocess.call(" python fO49.py 1", shell=True)
    def production(self):
        subprocess.call(" python fO410.py 1", shell=True)


    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 14 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 14 -weight bold -slant roman"  \
            " -underline 1 -overstrike 0"

        top.geometry("851x613+293+112")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.28, rely=0.08, height=41, width=354)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''SELECT DEPARTMENT''')
        self.Label1.configure(width=354)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.01, rely=0.29, height=34, width=227)
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''CIVIL''')
        self.Button1.configure(width=227)
        self.Button1.configure(command=self.civil)

        self.Button1_1 = Button(top)
        self.Button1_1.place(relx=0.35, rely=0.29, height=34, width=227)
        self.Button1_1.configure(activebackground="#f9f9f9")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#d9d9d9")
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font=font10)
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''COMPUTER''')
        self.Button1_1.configure(command=self.computer)

        self.Button1_1_1 = Button(top)
        self.Button1_1_1.place(relx=0.69, rely=0.29, height=34, width=227)
        self.Button1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1.configure(font=font10)
        self.Button1_1_1.configure(foreground="#000000")
        self.Button1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1.configure(highlightcolor="black")
        self.Button1_1_1.configure(pady="0")
        self.Button1_1_1.configure(text='''IT''')
        self.Button1_1_1.configure(command=self.it)

        self.Button1_1_1_1 = Button(top)
        self.Button1_1_1_1.place(relx=0.01, rely=0.47, height=34, width=227)
        self.Button1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1.configure(font=font10)
        self.Button1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1.configure(pady="0")
        self.Button1_1_1_1.configure(text='''ELECTRICAL''')
        self.Button1_1_1_1.configure(command=self.electrical)

        self.Button1_1_1_1_1 = Button(top)
        self.Button1_1_1_1_1.place(relx=0.36, rely=0.47, height=34, width=227)
        self.Button1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1.configure(font=font10)
        self.Button1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1.configure(text='''ELECTRCAL II''')
        self.Button1_1_1_1_1.configure(command=self.electricalii)

        self.Button1_1_1_1_1_1 = Button(top)
        self.Button1_1_1_1_1_1.place(relx=0.71, rely=0.47, height=34, width=227)
        self.Button1_1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1_1.configure(font=font10)
        self.Button1_1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1_1.configure(text='''E&TC''')
        self.Button1_1_1_1_1_1.configure(command=self.entc)

        self.Button1_1_1_1_1_1_1 = Button(top)
        self.Button1_1_1_1_1_1_1.place(relx=0.01, rely=0.67, height=34, width=227)
        self.Button1_1_1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1_1_1.configure(font=font10)
        self.Button1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1_1_1.configure(text='''ELECTRONICS II''')
        self.Button1_1_1_1_1_1_1.configure(command=self.electronicsii)

        self.Button1_1_1_1_1_1_1_1 = Button(top)
        self.Button1_1_1_1_1_1_1_1.place(relx=0.36, rely=0.67, height=34, width=227)
        self.Button1_1_1_1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1_1_1_1.configure(font=font10)
        self.Button1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1_1_1_1.configure(text='''MECHANICAL''')
        self.Button1_1_1_1_1_1_1_1.configure(command=self.mechanical)

        self.Button1_1_1_1_1_1_1_1_1 = Button(top)
        self.Button1_1_1_1_1_1_1_1_1.place(relx=0.71, rely=0.67, height=34, width=227)
        self.Button1_1_1_1_1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1_1_1_1_1.configure(font=font10)
        self.Button1_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1_1_1_1_1.configure(text='''MECHANICAL II''')
        self.Button1_1_1_1_1_1_1_1_1.configure(command=self.mechanical)

        self.Button1_1_1_1_1_1_1_1_1_1 = Button(top)
        self.Button1_1_1_1_1_1_1_1_1_1.place(relx=0.36, rely=0.85, height=34, width=227)
        self.Button1_1_1_1_1_1_1_1_1_1.configure(activebackground="#f9f9f9")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(activeforeground="#000000")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(background="#d9d9d9")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(font=font10)
        self.Button1_1_1_1_1_1_1_1_1_1.configure(foreground="#000000")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(highlightcolor="black")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(pady="0")
        self.Button1_1_1_1_1_1_1_1_1_1.configure(text='''PRODUCTION''')
        self.Button1_1_1_1_1_1_1_1_1_1.configure(command=self.production)






if __name__ == '__main__':
    vp_start_gui()



