#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.12
# In conjunction with Tcl version 8.6
#    Apr 05, 2018 07:37:37 PM

import sys
import pandas as pd
import sys
import tkMessageBox
import subprocess
from tkFileDialog import askopenfilename
try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import fo6_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel (root)
    fo6_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel (w)
    fo6_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel():
    global w
    w.destroy()
    w = None


class New_Toplevel:

    def browsefunc(self):
        filename = askopenfilename()
        self.Entry1.insert(0, filename)

    def search(self):
        if (self.Entry1.get() == ""):
            tkMessageBox.showinfo("PATH", "PLEASE PROVIDE APPROPRIATE PATH")
        else:
            name = self.Entry2.get();
            branch = self.Entry2_1.get();

            df = pd.read_excel(self.Entry1.get(), sheet_name='Sheet1')
            n = df['Name']
            d = df['Branch']
            f = 0
            for i in df.index:
                if n[i] == name and d[i] == branch:
                    a = n[i]
                    if f == 0:
                        tkMessageBox.showinfo("LOGIN PAGE", "RECORD FOUND IN DATABASE \n" + a)
                        f = 1

            if f == 0:
                tkMessageBox.showinfo("LOGIN PAGE", "RECORD NOT FOUND IN DATABASE")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 12 -weight bold -slant roman"  \
            " -underline 1 -overstrike 0"

        top.geometry("762x551+315+57")
        top.title("New Toplevel")
        top.configure(background="#595959")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")




        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.2, rely=0.27,height=40, relwidth=0.61)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.42, rely=0.82, height=34, width=127)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''SEARCH''')
        self.Button1.configure(command=self.search)

        self.Label2 = Label(top)
        self.Label2.place(relx=0.07, rely=0.51, height=31, width=134)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''ENTER NAME''')
        self.Label2.configure(width=134)

        self.Label2_1 = Label(top)
        self.Label2_1.place(relx=0.07, rely=0.65, height=31, width=134)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''ENTER BRANCH''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.58, rely=0.51,height=30, relwidth=0.32)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(width=244)

        self.Entry2_1 = Entry(top)
        self.Entry2_1.place(relx=0.58, rely=0.64,height=30, relwidth=0.32)
        self.Entry2_1.configure(background="white")
        self.Entry2_1.configure(disabledforeground="#a3a3a3")
        self.Entry2_1.configure(font="TkFixedFont")
        self.Entry2_1.configure(foreground="#000000")
        self.Entry2_1.configure(highlightbackground="#d9d9d9")
        self.Entry2_1.configure(highlightcolor="black")
        self.Entry2_1.configure(insertbackground="black")
        self.Entry2_1.configure(selectbackground="#c4c4c4")
        self.Entry2_1.configure(selectforeground="black")
        self.Entry2_1.configure(width=244)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.38, rely=0.09, height=34, width=177)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''BROWSE PATH''')
        self.Button2.configure(width=177)
        self.Button2.configure(command=self.browsefunc)





if __name__ == '__main__':
    vp_start_gui()



